name: Automation

on:
  workflow_dispatch:
    inputs:
      pr_ref:
        description: 'Pull Request Reference'
        required: true
      repo:
        description: 'Repository name'
        required: true
jobs:
  test-other-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pipeline Repository
        uses: actions/checkout@v4
        with:
          path: "tests"

      - name: Checkout Challenge Repository
        uses: actions/checkout@v4
        with:
          repository: "tiomika/${{ github.event.inputs.repo }}"
          ref: "refs/pull/${{ github.event.inputs.pr_ref }}/head"
          path: "sut"

      - name: Copy test files to challenge repository
        run: cp -r tests/calculadora/* sut/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # - name: Install Dependencies
      #   run: yarn install --frozen-lockfile
      #   working-directory: ./sut

      - name: Run Tests
        run: yarn test
        working-directory: ./sut
